FROM python:3.6
COPY requirements.txt /
RUN pip install -r /requirements.txt
RUN apt update
RUN apt -y upgrade \
  && apt -y install git build-essential libsqlite3-dev zlib1g-dev postgresql

# Create a directory and copy in all files
RUN mkdir -p /tmp/tippecanoe-src
RUN git clone https://github.com/mapbox/tippecanoe.git /tmp/tippecanoe-src
WORKDIR /tmp/tippecanoe-src

# Build tippecanoe
RUN make install

# Remove the temp directory and unneeded packages
WORKDIR /
RUN rm -rf /tmp/tippecanoe-src \
  && apt-get -y remove --purge build-essential && apt-get -y autoremove
  