CREATE EXTENSION postgis;

CREATE TABLE IF NOT EXISTS poi
(
    id SERIAL NOT NULL,
    business_name CHARACTER VARYING(64) DEFAULT NULL::CHARACTER VARYING,
    address CHARACTER VARYING(165) DEFAULT NULL::CHARACTER VARYING,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    brand_name CHARACTER VARYING(164) DEFAULT NULL::CHARACTER VARYING,
    brand_id INTEGER,
    category_name CHARACTER VARYING(164) DEFAULT NULL::CHARACTER VARYING,
    category_id INTEGER,
    polygons public.geometry
);
