name: Makefile CI



on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
      
    - name: Install dependencies
      
      env:
            MAPBOX_ACCESS_TOKEN: ${{ env.MAPBOX_ACCESS_TOKEN }}
      run: make run-poi
      
    - name: Run check
      run: make run-state
      

