name: Makefile CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:


    steps:
    - uses: actions/checkout@v3
    
      
    - name: Install dependencies
      env:
        MAPBOX_ACCESS_TOKEN: sk.eyJ1Ijoic2hhbGluaTEyOTciLCJhIjoiY2w3NGVhdTgzMGF6YjNucGVvdjd3ZTFmdiJ9.0sfPv8vfNqcSNQqKM1wlpA
      run: make run-poi
      
    - name: Run check
      run: make run-state
      

